"""
One-time setup: create an ElevenLabs Conversational AI agent that:
  - uses our Groq/LangGraph sales agent as a CUSTOM LLM (via {PUBLIC_URL}/v1/chat/completions)
  - speaks with the expressive `eleven_v3_conversational` model so audio tags
    like [laughs] / [sighs] and "..." pauses are actually performed.

Run from backend/sales_agent_service/src with the venv python:
    ..\.venv\Scripts\python.exe setup_elevenlabs_agent.py

It prints the new agent id and writes ELEVENLABS_AGENT_ID into .env.
"""

import os
import re
import sys

import requests
from dotenv import load_dotenv

load_dotenv()

API_BASE = "https://api.elevenlabs.io/v1"
API_KEY = os.getenv("eleven_labs_key")
PUBLIC_URL = (os.getenv("PUBLIC_URL") or "").rstrip("/")

# A short cosmetic prompt for the dashboard. The actual replies come from our custom
# LLM endpoint (Groq + LangGraph), which uses its own personas/company data.
AGENT_PROMPT = (
    "You are Alex, a friendly, concise human sales representative at TechCare AI. "
    "Replies are generated by a custom backend; keep the call natural and engaging."
)

FIRST_MESSAGE = "Hey! This is Alex from TechCare AI... do you have a quick minute to chat?"

# Existing brand voice used elsewhere in the project.
PRIMARY_VOICE = "IKne3meq5aSn9XLyUdCD"
# ElevenLabs default conversational voice (fallback).
FALLBACK_VOICE = "cjVigY5qzO86Huf0OWal"


def build_config(tts_model: str, voice_id: str) -> dict:
    return {
        "name": "TechCare AI Sales Agent (Alex)",
        "conversation_config": {
            "agent": {
                "first_message": FIRST_MESSAGE,
                "language": "en",
                "prompt": {
                    "prompt": AGENT_PROMPT,
                    "llm": "custom-llm",
                    "custom_llm": {
                        # Base URL only — ElevenLabs appends "/chat/completions".
                        "url": f"{PUBLIC_URL}/v1",
                        "model_id": "sales-agent",
                    },
                },
            },
            "tts": {
                "model_id": tts_model,
                "voice_id": voice_id,
                "stability": 0.5,
            },
        },
    }


def try_create(config: dict):
    resp = requests.post(
        f"{API_BASE}/convai/agents/create",
        headers={"xi-api-key": API_KEY, "Content-Type": "application/json"},
        json=config,
        timeout=30,
    )
    return resp


def write_env_var(path: str, key: str, value: str) -> None:
    if not os.path.exists(path):
        return
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    line = f"{key}={value}"
    if re.search(rf"(?m)^{re.escape(key)}=.*$", content):
        content = re.sub(rf"(?m)^{re.escape(key)}=.*$", line, content)
    else:
        if content and not content.endswith("\n"):
            content += "\n"
        content += line + "\n"

    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def main():
    if not API_KEY:
        print("ERROR: eleven_labs_key missing in .env")
        sys.exit(1)
    if not PUBLIC_URL:
        print("ERROR: PUBLIC_URL missing in .env (your ngrok https URL)")
        sys.exit(1)

    print(f"Custom LLM URL  : {PUBLIC_URL}/v1/chat/completions")

    # Prefer the expressive v3 model (real laughs/pauses); fall back if unavailable.
    attempts = [
        ("eleven_v3_conversational", PRIMARY_VOICE),
        ("eleven_v3_conversational", FALLBACK_VOICE),
        ("eleven_flash_v2_5", PRIMARY_VOICE),
        ("eleven_turbo_v2_5", PRIMARY_VOICE),
    ]

    last_error = None
    for tts_model, voice_id in attempts:
        print(f"\nCreating agent with TTS model='{tts_model}', voice='{voice_id}' ...")
        resp = try_create(build_config(tts_model, voice_id))
        if resp.ok:
            data = resp.json()
            agent_id = data.get("agent_id") or data.get("agentId")
            print("\n=========================================")
            print(f"SUCCESS - agent created")
            print(f"agent_id   : {agent_id}")
            print(f"TTS model  : {tts_model}")
            if tts_model != "eleven_v3_conversational":
                print("NOTE: v3 expressive model was not available on this account,")
                print("      so [laughs]/[sighs] tags will NOT be performed (read as text).")
            print("=========================================")

            for env_path in (".env", os.path.join("..", "..", ".env")):
                write_env_var(env_path, "ELEVENLABS_AGENT_ID", agent_id)
            print("Wrote ELEVENLABS_AGENT_ID to .env")
            return

        last_error = f"{resp.status_code}: {resp.text}"
        print(f"  failed -> {last_error}")

    print("\nAll attempts failed. Last error:")
    print(last_error)
    print(
        "\nIf this is a 401/403, your ElevenLabs plan may not include Conversational AI / "
        "Custom LLM. Check the dashboard (Conversational AI must be enabled)."
    )
    sys.exit(1)


if __name__ == "__main__":
    main()
